spring.application.name=VeritasBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/veritas_test
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.main.lazy-initialization=true

security.jwt.secret-key=bJipVMJYV06xAvwe1B9jBzvkKVjdnXd7H4gKeWR9tyI
security.jwt.expiration=3600000
