plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0' // Change this to 3.4.2 if 4.1.0 was a typo
    id 'io.spring.dependency-management' version '1.1.7'
    id 'eclipse'
}

ext {
    lombokVersion = "1.18.46"
    mapstructVersion = "1.6.3"
    lombokMapstructBindingVersion = "0.2.0"
}

group = 'dev.sid'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

eclipse {
    project {
        name = "VeritasBackend"
      }
  }


repositories {
    mavenCentral()
}

dependencies {

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    runtimeOnly 'org.postgresql:postgresql'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
    testRuntimeOnly 'com.h2database:h2'

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"

    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    
    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
}

tasks.named('test') {
    useJUnitPlatform()
}

allprojects {
    tasks.withType(JavaCompile) {
        options.compilerArgs += [
            '-Amapstruct.verbose=true',
            '-Amapstruct.defaultComponentModel=spring'
        ]
    }
}
