/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.example.Core.Token;
import org.example.Expression.AssignExpression;
import org.example.Expression.Expression;
import org.example.Graph.GraphBuilderVisitor;
import org.example.Utils.TokenType;
import org.example.Graph.ComponentNode;

public class LibraryTest {
  @Test
  public void LexBasic() {
    Library classUnderTest = new Library("1 + 1");
    List<Token> res = classUnderTest.runLexer();
    List<Token> expected = List.of(new Token(TokenType.NUMBER, "1"), new Token(TokenType.ADD, "+"),
        new Token(TokenType.NUMBER, "1"),
        new Token(TokenType.EOF, "EOF"));

    assertEquals(expected, res);
  }

  @Test
  public void LexCorrectly() {
    Library classUnderTest = new Library("23 * 12 + 34 / 56");
    List<Token> res = classUnderTest.runLexer();
    List<Token> expected = List.of(
        new Token(TokenType.NUMBER, "23"),
        new Token(TokenType.MUL, "*"),
        new Token(TokenType.NUMBER, "12"),
        new Token(TokenType.ADD, "+"),
        new Token(TokenType.NUMBER, "34"),
        new Token(TokenType.DIV, "/"),
        new Token(TokenType.NUMBER, "56"),
        new Token(TokenType.EOF, "EOF"));
    assertEquals(expected, res);
  }

  @Test
  public void LexVarsCorrectly() {
    Library classUnderTest = new Library("BASIC * 2");
    List<Token> res = classUnderTest.runLexer();
    List<Token> expected = List.of(
        new Token(TokenType.IDENT, "BASIC"),
        new Token(TokenType.MUL, "*"),
        new Token(TokenType.NUMBER, "2"),
        new Token(TokenType.EOF, "EOF"));
    assertEquals(expected, res);
  }

  @Test
  public void LexEqualsCorrectly() {
    Library classUnderTest = new Library("BASIC = HRA * 2");
    List<Token> res = classUnderTest.runLexer();
    List<Token> expected = List.of(
        new Token(TokenType.IDENT, "BASIC"),
        new Token(TokenType.EQUAL, "="),
        new Token(TokenType.IDENT, "HRA"),
        new Token(TokenType.MUL, "*"),
        new Token(TokenType.NUMBER, "2"),
        new Token(TokenType.EOF, "EOF"));
    assertEquals(expected, res);
  }

  @Test
  public void LexLessThanCorrectly() {
    Library classUnderTest = new Library("BASIC <= HRA");
    List<Token> res = classUnderTest.runLexer();
    List<Token> expected = List.of(
        new Token(TokenType.IDENT, "BASIC"),
        new Token(TokenType.ELT, "<="),
        new Token(TokenType.IDENT, "HRA"),
        new Token(TokenType.EOF, "EOF"));
    assertEquals(expected, res);
  }

  @Test
  public void parseCorrectly() {
    Library classUnderTest = new Library("1 + 1");
    String res = classUnderTest.runParser();
    String expected = "(+ 1 1)";
    assertEquals(expected, res);
  }

  @Test
  public void parseVarsCorrectly() {
    Library classUnderTest = new Library("BASIC * 2");
    String res = classUnderTest.runParser();
    String expected = "(* BASIC 2)";
    assertEquals(expected, res);
  }

  @Test
  public void parseEqualsCorrectly() {
    Library classUnderTest = new Library("BASIC = HRA * 2");
    String res = classUnderTest.runParser();
    String expected = "(= BASIC (* HRA 2))";
    assertEquals(expected, res);
  }

  @Test
  public void parseTest() {
    String input = "BASIC = HRA * 2\nHRA = PF * 4";
    Library classUnderTest = new Library(input);

    List<Expression> expr = classUnderTest.runParser(input);

    Map<String, ComponentNode> components = new HashMap<>();

    for (Expression e : expr) {
      AssignExpression assignExpression = (AssignExpression) e;

      ComponentNode node = new ComponentNode(assignExpression.getName().getName(), assignExpression);
      System.out.println(node.getName());

      components.put(assignExpression.getName().getName(), node);
    }

    GraphBuilderVisitor graphBuilderVisitor = new GraphBuilderVisitor(components);

    for (ComponentNode node : components.values()) {
      graphBuilderVisitor.setCurrent(node);
      node.getExpression().accept(graphBuilderVisitor);
    }

    for (ComponentNode node : components.values()) {
      System.out.print(node.getName() + " depends on: ");

      System.out.println("Dependencies: " + node.getDependencies().size());
      for (ComponentNode dep : node.getDependencies()) {
        System.out.print(dep.getName() + " is the dependency\n");
      }

      System.out.println();
    }

    // for (Expression e : expr) {
    // System.out.println(e.getClass());
    // }
  }
}
