/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import org.example.Expression.AssignExpression;
import org.example.Expression.Expression;
import org.example.Graph.GraphBuilderVisitor;
import org.example.Graph.ComponentNode;
import org.example.Graph.CycleDetection;
import org.example.Graph.Evaluator;

public class LibraryTest {

  @Test
  public void parseTest() {
    String input = "Basic = 50000\nHRA = Basic * 0.4\nPF = Basic * 0.12\nNet = Basic + HRA - PF";
    PayrollEngine classUnderTest = new PayrollEngine(input);

    List<Expression> expr = classUnderTest.runParser(input);

    Map<String, ComponentNode> components = new HashMap<>();

    System.out.println("Number of nodes: " + expr.size());
    for (Expression e : expr) {
      AssignExpression assignExpression = (AssignExpression) e;

      ComponentNode node = new ComponentNode(assignExpression.getName().getName(), assignExpression);
      System.out.println(node.getName());

      components.put(assignExpression.getName().getName(), node);
    }

    System.out.println();
    GraphBuilderVisitor graphBuilderVisitor = new GraphBuilderVisitor(components);

    for (ComponentNode node : components.values()) {
      graphBuilderVisitor.setCurrent(node);
      node.getExpression().accept(graphBuilderVisitor);
    }

    for (ComponentNode node : components.values()) {
      System.out.println(node.getName() + " : ");

      System.out.println("Dependencies are : ");
      if (node.getDependencies().size() == 0) {
        System.out.println("None");
      } else {
        for (ComponentNode dep : node.getDependencies()) {
          System.out.print(dep.getName() + " ,");
        }
        System.out.println();
      }

      System.out.println("Dependents: ");
      if (node.getDependents().size() == 0) {
        System.out.println("None");
      } else {
        for (ComponentNode dep : node.getDependents()) {
          System.out.print(dep.getName() + " ,");
        }
        System.out.println();
      }
      System.out.println();
    }

    List<ComponentNode> sorted = CycleDetection.topologicalSort(components);

    System.out.println("Topological sort: ");

    Map<String, BigDecimal> values = new HashMap<>();

    Evaluator evaluator = new Evaluator(values);

    for (ComponentNode node : sorted) {
      BigDecimal value = node.getExpression().accept(evaluator);
      values.put(node.getName(), value);
    }

    System.out.println("Evaluator Map : ");
    for (Entry<String, BigDecimal> entry : values.entrySet()) {
      System.out.println(entry.getKey() + " : " + entry.getValue());
    }
  }
}
