/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.List;
import org.example.Core.Token;
import org.example.Utils.TokenType;

public class LibraryTest {
  @Test
  public void LexBasic() {
    Library classUnderTest = new Library("1 + 1");
    List<Token> res = classUnderTest.runLexer();
    List<Token> expected = List.of(new Token(TokenType.NUMBER, "1"), new Token(TokenType.ADD, "+"),
        new Token(TokenType.NUMBER, "1"),
        new Token(TokenType.EOF, "EOF"));

    assertEquals(expected, res);
  }

  @Test
  public void LexCorrectly() {
    Library classUnderTest = new Library("23 * 12 + 34 / 56");
    List<Token> res = classUnderTest.runLexer();
    List<Token> expected = List.of(
        new Token(TokenType.NUMBER, "23"),
        new Token(TokenType.MUL, "*"),
        new Token(TokenType.NUMBER, "12"),
        new Token(TokenType.ADD, "+"),
        new Token(TokenType.NUMBER, "34"),
        new Token(TokenType.DIV, "/"),
        new Token(TokenType.NUMBER, "56"),
        new Token(TokenType.EOF, "EOF"));
    assertEquals(expected, res);
  }

  @Test
  public void LexVarsCorrectly() {
    Library classUnderTest = new Library("BASIC * 2");
    List<Token> res = classUnderTest.runLexer();
    List<Token> expected = List.of(
        new Token(TokenType.IDENT, "BASIC"),
        new Token(TokenType.MUL, "*"),
        new Token(TokenType.NUMBER, "2"),
        new Token(TokenType.EOF, "EOF"));
    assertEquals(expected, res);
  }

  @Test
  public void LexEqualsCorrectly() {
    Library classUnderTest = new Library("BASIC = HRA * 2");
    List<Token> res = classUnderTest.runLexer();
    List<Token> expected = List.of(
        new Token(TokenType.IDENT, "BASIC"),
        new Token(TokenType.EQUAL, "="),
        new Token(TokenType.IDENT, "HRA"),
        new Token(TokenType.MUL, "*"),
        new Token(TokenType.NUMBER, "2"),
        new Token(TokenType.EOF, "EOF"));
    assertEquals(expected, res);
  }

  @Test
  public void LexLessThanCorrectly() {
    Library classUnderTest = new Library("BASIC <= HRA");
    List<Token> res = classUnderTest.runLexer();
    List<Token> expected = List.of(
        new Token(TokenType.IDENT, "BASIC"),
        new Token(TokenType.ELT, "<="),
        new Token(TokenType.IDENT, "HRA"),
        new Token(TokenType.EOF, "EOF"));
    assertEquals(expected, res);
  }

  @Test
  public void parseCorrectly() {
    Library classUnderTest = new Library("1 + 1");
    String res = classUnderTest.runParser();
    String expected = "(+ 1 1)";
    assertEquals(expected, res);
  }

  @Test
  public void parseVarsCorrectly() {
    Library classUnderTest = new Library("BASIC * 2");
    String res = classUnderTest.runParser();
    String expected = "(* BASIC 2)";
    assertEquals(expected, res);
  }

  @Test
  public void parseEqualsCorrectly() {
    Library classUnderTest = new Library("BASIC = HRA * 2");
    String res = classUnderTest.runParser();
    String expected = "(= BASIC (* HRA 2))";
    assertEquals(expected, res);
  }
}
