/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.example.Core.LangParser;
import org.example.Core.Lexer;
import org.example.Expression.AssignExpression;
import org.example.Expression.Expression;
import org.example.Graph.ComponentNode;
import org.example.Graph.CycleDetection;
import org.example.Graph.Evaluator;
import org.example.Graph.GraphBuilderVisitor;
import org.example.Utils.CharacterStream;

public class PayrollEngine {
  public Map<String, BigDecimal> evaluate(String rules) {
    String[] input = rules.split("\\n");
    List<Expression> expArr = new ArrayList<>();
    Lexer lex = new Lexer();
    for (String line : input) {
      lex.setStream(new CharacterStream(line));
      Expression exp = new LangParser(lex).parseExpression();
      expArr.add(exp);
    }

    Map<String, ComponentNode> comp = new HashMap<>();

    for (Expression exp : expArr) {
      AssignExpression assign = (AssignExpression) exp;

      ComponentNode node = new ComponentNode(assign.getName().getName(), assign.getRight());

      comp.put(assign.getName().getName(), node);
    }

    GraphBuilderVisitor builder = new GraphBuilderVisitor(comp);

    for (ComponentNode node : comp.values()) {
      builder.setCurrent(node);
      node.getExpression().accept(builder);
    }

    List<ComponentNode> sorted = CycleDetection.topologicalSort(comp);

    Map<String, BigDecimal> values = new HashMap<>();
    Evaluator eval = new Evaluator(values);

    for (ComponentNode node : sorted) {
      BigDecimal bd = node.getExpression().accept(eval);
      values.put(node.getName(), bd);
    }

    return values;
  }
}
