/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

import org.example.Core.LangParser;
import org.example.Core.Lexer;
import org.example.Core.Token;
import org.example.Expression.Expression;

public class Library {
  Lexer lexer;
  String input;

  public Library(String input) {
    this.input = input;
    lexer = new Lexer(this.input);
  }

  public List<Token> runLexer() {
    return lexer.lex();
  }

  public String runParser() {
    Expression expression = new LangParser(lexer).parseExpression();
    StringBuilder sb = new StringBuilder();
    expression.print(sb);
    return sb.toString();
  }
}
